language: ruby
cache: bundler
rvm:
  - 2.7.1
addons:
  apt:
    packages:
      - openjdk-8-jre
before_install:
  - gem update --system
  - gem install bundler
  - nvm install node
install:
  - bundle install --jobs=3 --retry=3
  - npm install -g pa11y-ci
script:
  - bundle exec jekyll clean && bundle exec jekyll build
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: master
